<section id="options">
    <aside>
        <?php include ROOT_PATH . '/template/view/body/Description.phtml' ?>
    </aside>
    <?php include ROOT_PATH . '/template/view/body/Filters.phtml' ?>
</section>
<section id="graphic">
    <div class="container">
        <h2>Sorting</h2>
        <nav id='sorting'>

        </nav>
        <div id="svg">
            <div class="container">
                <h3>Timed keys</h3>
                <div id="graphic-container">

                </div>
                <div id="horizontal-line" class="hidden"></div>
                <div id="vertical-line" class="hidden"></div>
                <div id="detail" class="hidden hover-container"></div>
                <div id="details" class="hidden"></div>
            </div>
        </div>
    </div>
</section>