<p>
    Copyright © 2020-2023 Optimal-Deplete
    <a href="https://github.com/Mickael-Bidinger/Optimal-Deplete" target="_blank" title="gitHub" aria-label="gitHub">
        <i class="fa fa-github-square"></i>
    </a>
</p>
<aside>
    <p>
        J'ai développé cette application pour mon projet de fin d'études (développeur/intégrateur d'applications web).
        <br>
        Je suis maintenant à la recherche d'un emploi.
        Retrouvez-moi sur
        <a
                href="https://www.linkedin.com/in/mickael-bidinger/"
                target="_blank"
                title="linked-in"
                aria-label="linked-in"
        >
            <i class="fa fa-linkedin-square"></i>
        </a>
    </p>
    <p>
        As this website is my end-of-study project, I'm currently looking for a job. Find me on
        <a
                href="https://www.linkedin.com/in/mickael-bidinger/"
                target="_blank"
                title="linked-in"
                aria-label="linked-in"
        >
            <i class="fa fa-linkedin-square"></i>
        </a>
    </p>
</aside>
<p>
    Factions illustrations belong to
    <a href="https://www.deviantart.com/popokupingupop90"
       target="_blank"
       title="PopokuPinguPop90 page"
       aria-label="PopokuPinguPop90 page">PopokuPinguPop90</a>
</p>