<h2>What is Optimal-Deplete ?</h2>
<p>
    This website allows you to check what percentage of finished <strong>keys</strong> are done
    <strong>in time</strong>.
</p>
<p>
    You can choose to sort and/or filter your results by <strong>specialization</strong>(s), <strong>class</strong>(es),
    <strong>dungeon</strong>(s), <strong>key</strong> level(s)...
</p>
<p>
    Now <strong>blizzard</strong> only records finished <strong>keys</strong>, meaning that every started one is
    not necessarily taken into account while calculating these <strong>statistics</strong>.
    <br><i>Therefore, the number of <strong>timed keys</strong> is overestimated.</i>
</p>