<div class="container" id="filter">
    <h2>Filters</h2>
    <a href="<?= RELATIVE_ROOT_PATH ?>/" data-type="reset" data-reset="all" class="small right hidden">Reset</a>
    <?php include ROOT_PATH . '/template/view/body/options/Menu.phtml' ?>
    <div id="specialization" data-type="filter" data-option="specialization" class="hidden"></div>
    <div id="dungeon" data-type="filter" data-option="dungeon" class="hidden"></div>
    <div id="affix" data-type="filter" data-option="affix" class="hidden"></div>
    <div id="level" data-type="filter" data-option="level" class="hidden"></div>
    <div id="faction" data-type="filter" data-option="faction" class="hidden"></div>

</div>