<nav id="menu">
    <ul>
        <li>
            <a href="#specialization"
               data-type="filter"
               data-option="specialization"
               aria-label="Select specialization(s)"
               title="Select specialization(s)"
            >
                Specialization<i class="fa fa-check"></i><i class="fa fa-caret-down"></i>
            </a>
        </li>
        <li>
            <a href="#dungeon"
               data-type="filter"
               data-option="dungeon"
               aria-label="Select dungeon(s)"
               title="Select dungeon(s)"
            >
                Dungeon<i class="fa fa-check"></i><i class="fa fa-caret-down"></i>
            </a>
        </li>
        <li>
            <a href="#level"
               data-type="filter"
               data-option="level"
               aria-label="Select key-level(s)"
               title="Select key-level(s)"
            >
                Key level<i class="fa fa-check"></i><i class="fa fa-caret-down"></i>
            </a>
        </li>
        <li>
            <a href="#faction"
               data-type="filter"
               data-option="faction"
               aria-label="Select faction(s)"
               title="Select faction(s)"
            >
                Faction<i class="fa fa-check"></i><i class="fa fa-caret-down"></i>
            </a>
        </li>
        <li>
            <a href="#affix"
               data-type="filter"
               data-option="affix"
               aria-label="Select affix(es)"
               title="Select affix(es)"
            >
                Affix<i class="fa fa-check"></i><i class="fa fa-caret-down"></i>
            </a>
        </li>
    </ul>
</nav>